### ISSUE TITLE
500 SERVER ERROR

### ISSUE THREAD

**Issue by Dancbeunny98** [Status-Page/Status-Page#110]
Im am delete tetrick group amd create new = error how fix?
```
**Additional context**
[2021-07-01 22:11:02] production.ERROR: The payload is invalid. {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:196)
[stacktrace]
#0 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(137): Illuminate\\Encryption\\Encrypter->getJsonPayload()
#1 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(165): Illuminate\\Encryption\\Encrypter->decrypt()
#2 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Encryption\\Encrypter->decryptString()
#3 /var/www/statuspage/app/Models/Setting.php(22): Illuminate\\Support\\Facades\\Facade::__callStatic()
#4 /var/www/statuspage/app/Console/Commands/FetchUptimeRobotData.php(48): App\\Models\\Setting::getString()
#5 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\FetchUptimeRobotData->handle()
#6 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#10 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#11 /var/www/statuspage/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#12 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/statuspage/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#14 /var/www/statuspage/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /var/www/statuspage/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#16 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#17 /var/www/statuspage/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 /var/www/statuspage/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}
"}
```

**Comment by HerrTxbias** [comment]
Hello,
thank you for your request. Unfortunately you didn't use the "Bug report" template, where some important information must be filled in. Without this information it will be very difficult to track the bug or fix it afterwards. [Please recreate the issue](https://github.com/Status-Page/Status-Page/issues/new?assignees=&labels=&template=bug_report.md&title=) and fill in the template completely.
Many greetings
