### ISSUE TITLE
[Bug]: Unable to subscribe if not connected on dashboard

### ISSUE THREAD

**Issue by Emma0Z** [Status-Page/Status-Page#588]
### Description of the Bug

So it's been a whole day, during the test we see this behavior. 
We are now sure it was a thing.

When you aren't connected on Dashboard, you get an `error 500` while you are trying to subscribe yourself.
Go back and retry. You have a print that you are now subscribe.

In fact, when you are back into the dashboard and go to subscribers section, you see the email address.
But with this behavior, you will not be able to receive any alert because, you can't verify your email (it's blocked before).

With the output print, you will see the subscribers section, need to be logged in for subscribing.
For seeing the error, don't forget to enable **DEBUG** mode into the `configuration.py`

I'll do a PR right after, we solved this by restoring some codes.

### Expected behavior

When you subscribe, you'll be able to receive instantly your email verification.

### Reproduction

1. Go to 'your status page'
2. Verify you are not logged into dashboard
3. Then click son subscribe
4. Enter email and click subscribe
5. See error

### Version

> 2.0.0 (Preview)

### Information about your Device

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser Firefox
 - Version  116.0.2

**Smartphone (please complete the following information):**
 - Device: Nothing Phone (1)
 - OS: Android 13
 - Browser Brave
 - Version 1.56.20

### Relevant log output

```shell
Aug 17 13:22:42 some-server gunicorn[6716]: Internal Server Error: /subscribers/subscribe
Aug 17 13:22:42 some-server gunicorn[6716]: Traceback (most recent call last):
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
Aug 17 13:22:42 some-server gunicorn[6716]:     response = get_response(request)
Aug 17 13:22:42 some-server gunicorn[6716]:                ^^^^^^^^^^^^^^^^^^^^^
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
Aug 17 13:22:42 some-server gunicorn[6716]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Aug 17 13:22:42 some-server gunicorn[6716]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
Aug 17 13:22:42 some-server gunicorn[6716]:     return self.dispatch(request, *args, **kwargs)
Aug 17 13:22:42 some-server gunicorn[6716]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
Aug 17 13:22:42 some-server gunicorn[6716]:     return handler(request, *args, **kwargs)
Aug 17 13:22:42 some-server gunicorn[6716]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/statuspage/statuspage/views/subscriber.py", line 70, in post
Aug 17 13:22:42 some-server gunicorn[6716]:     subscriber.save()
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/statuspage/subscribers/models.py", line 56, in save
Aug 17 13:22:42 some-server gunicorn[6716]:     super().save(*args, **kwargs)
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
Aug 17 13:22:42 some-server gunicorn[6716]:     self.save_base(
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/db/models/base.py", line 892, in save_base
Aug 17 13:22:42 some-server gunicorn[6716]:     post_save.send(
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
Aug 17 13:22:42 some-server gunicorn[6716]:     return [
Aug 17 13:22:42 some-server gunicorn[6716]:            ^
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
Aug 17 13:22:42 some-server gunicorn[6716]:     (receiver, receiver(signal=self, sender=sender, **named))
Aug 17 13:22:42 some-server gunicorn[6716]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/statuspage/extras/signals.py", line 71, in handle_changed_object
Aug 17 13:22:42 some-server gunicorn[6716]:     objectchange.user = request.user
Aug 17 13:22:42 some-server gunicorn[6716]:     ^^^^^^^^^^^^^^^^^
Aug 17 13:22:42 some-server gunicorn[6716]:   File "/opt/status-page/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 266, in __set__
Aug 17 13:22:42 some-server gunicorn[6716]:     raise ValueError(
Aug 17 13:22:42 some-server gunicorn[6716]: ValueError: Cannot assign "<SimpleLazyObject: <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f76c7895490>>>": "ObjectChange.user" must be a "User" instance.
```

**Comment by HerrTxbias** [comment]
PR has been merged

**Comment by HerrTxbias** [comment]
Thank you for the fix!
