### ISSUE TITLE
[Bug]: ImportError: cannot import name 'resolve_connection' from 'rq.connections'

### ISSUE THREAD

**Issue by spitzlei** [Status-Page/Status-Page#651]
### Description of the Bug

ImportError: cannot import name 'resolve_connection' from 'rq.connections'

-> resolve_connection (rq packages) is deprecated and already removed. 

Can't start status-page anymore.

### Expected behavior

Start status-page.

### Reproduction

1. Checkout current code
2. Run installation

### Version

= 2.0.0 (Stable)

### Information about your Device

**Desktop (please complete the following information):**
 - OS: Linux

### Relevant log output

```shell
[2024-10-29 09:26:07 +0100] [39] [ERROR] Exception in worker process
 Traceback (most recent call last):
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
     worker.init_process()
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
     super().init_process()
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
     self.load_wsgi()
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
     self.wsgi = self.app.wsgi()
                 ^^^^^^^^^^^^^^^
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
     self.callable = self.load()
                     ^^^^^^^^^^^
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
     return self.load_wsgiapp()
            ^^^^^^^^^^^^^^^^^^^
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
     return util.import_app(self.app_uri)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/src/app/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
     mod = importlib.import_module(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
   File "/usr/src/app/statuspage/statuspage/wsgi.py", line 16, in <module>
     application = get_wsgi_application()
                   ^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/src/app/venv/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
     django.setup(set_prefix=False)
   File "/usr/src/app/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
     apps.populate(settings.INSTALLED_APPS)
   File "/usr/src/app/venv/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
     app_config.ready()
   File "/usr/src/app/statuspage/queuing/apps.py", line 15, in ready
     scheduler = django_rq.get_scheduler('default')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/src/app/venv/lib/python3.12/site-packages/django_rq/queues.py", line 363, in get_scheduler
     return scheduler_class(
            ^^^^^^^^^^^^^^^^
   File "/usr/src/app/venv/lib/python3.12/site-packages/rq_scheduler/scheduler.py", line 33, in __init__
     from rq.connections import resolve_connection
 ImportError: cannot import name 'resolve_connection' from 'rq.connections' (/usr/src/app/venv/lib/python3.12/site-packages/rq/connections.py)
```

**Comment by herrtxbias** [comment]
Only python3.12 seem to be affected by this bug. Will look into this!

**Comment by herrtxbias** [comment]
This issue has been resolved by bumping "rq-scheduler" to its latest version. I've gone ahead and update all dependencies to its latest version: https://github.com/Status-Page/Status-Page/commit/c7d57be3f1a61b99b3828fbc3d1e99bf5224ddef
